### ISSUE TITLE
Fuzz testing doesn`t insert naughtystrings in scenario

### ISSUE THREAD

**Issue by prudn** [shoreditch-ops/artillery-plugin-fuzzer#2]
Hello team!

Thanks for great plugin!
Unfortunately {{naughtyString}} directive doesn`t insert any lines in running scenario.

Scenario:
-----
config:
  target: "https://BLABLASITE.com"
  processor: "./functions.js"
  phases:
    - duration: 300
      arrivalRate: 1
  plugins:
    statsd:
      host: "ststsdServer"
      port: 8125
      prefix: "Artillery.PT.Pub1"
  config:
    plugins:
      fuzzer: {}
scenarios:
- name: Search
  weight: 2
  flow:
  - get:
      url: "http://BLABLASITE.com/search.html?q={{naughtyString}}&tab=products"
      afterResponse: "toConsole"
-----

**Comment by hassy** [comment]
I think the problem is that you have two separate `plugins` entries in your config. Both plugin configurations should be under the same `plugins` key.

**Comment by prudn** [comment]
Thank you. Problem solved. Now plugin works brilliantly.
