### ISSUE TITLE
I get "Errors:     The header content contains invalid characters: 127"

### ISSUE THREAD

**Issue by blueelvis** [shoreditch-ops/artillery-plugin-fuzzer#5]
When using the {{naughtyString}} in the Header section, I get the following -

![image](https://user-images.githubusercontent.com/6985763/38422170-5efab88a-39c7-11e8-8ef0-63380dd6daad.png)

Any idea what could be happening?

**Comment by blueelvis** [comment]
@hassy - But then don't you think that this is kind of a major limitation? I need to fuzz headers as well :(

**Comment by hassy** [comment]
It is a limitation but not major enough for us to warrant writing a custom HTTP client. If you need to fuzz headers, you can try combining naughty strings with something like `nc`.
